---
openapi: 3.0.1
info:
  title: Blog app API V1
  version: v1
paths: {}
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
